- .gitignore
- src/suit/config/web.xml
- src/suit/html/main.html
- src/suit/html/ts.html
- src/suit/js/SUIT.js
- src/suit/js/actions.jsx
see pull request:  https://github.com/Caltech-IPAC/firefly/pull/325
> DM-7803: add time series launch capability to suit app.

- src/suit/html/suit.html
https://jira.lsstcorp.org/browse/DM-12993
The changes are mostly in Firefly. 
Please see test details in the corresponding Firefly PR.
https://github.com/Caltech-IPAC/firefly/pull/523
This PR if for using multi-trace charts in SUIT
- use multi-trace charts
> DM-12993 Add NEOWISE data to PDAC search panel

- config/app.config
- config/common.prop
- config/k8s/suit.yaml
https://jira.lsstcorp.org/browse/DM-17072
Firefly PR: https://github.com/Caltech-IPAC/firefly/pull/719
> DM-17072 re-establish the legacy PDAC portal

- config/app.config
- config/common.prop
- config/k8s/suit-int.yaml
- config/k8s/suit-stable.yaml
- src/suit/build.gradle
- src/suit/java/edu/caltech/ipac/lsst/security/LsstSsoAdapter.java
- src/suit/js/SUIT.js
- src/suit/js/suit.css
https://jira.lsstcorp.org/browse/DM-14501
Add authentication hook for LSST portal to CILogon.
- fix IRSA https only problem
> Dm 14501 add lsst auth adapter

- .gitignore
- build.gradle
- buildScript/depends.gincl
- buildScript/global.gincl
- buildScript/init.gincl
- config/app.config
- src/suit/build.gradle
- src/suit/package.json
- src/suit/test/edu/caltech/ipac/firefly/server/query/LSSTDbServTest.java
- src/suit/test/edu/caltech/ipac/firefly/server/query/LSSTImgServTest.java
https://jira.lsstcorp.org/browse/DM-17793
Setup Jest and JUnit test framework for suit
- also move LSST tests from firefly to suit
To test:
- checkout firefly and suit
- in suit:  `gradle :suit:test`
This will run both firefly and suit tests.
> Dm 17793 update test framework

- config/k8s/suit-int.yaml
- config/k8s/suit-stable.yaml
https://jira.lsstcorp.org/browse/DM-19858
Please test.  https://lsst-lsp-int.ncsa.illinois.edu/portal/suit
This link should redirect to https://lsst-lsp-int.ncsa.illinois.edu/portal/suit/.
> DM-19858: Ensure that Portal/Firefly deployments are insensitive to trailing slashes on the application root

- src/suit/html/slate.html
https://github.com/Caltech-IPAC/firefly/pull/961
> FIREFLY-521: add RequireWebSocketUptime

- src/suit/java/edu/caltech/ipac/lsst/security/LsstSsoAdapter.java
Gafaelfawr 2.0, used for authentication in the Rubin Science Platform,
no longer uses JWTs for tokens and therefore the old token parsing
code no longer works.  Replace this with code that extracts user
information from the headers that are set by the NGINX auth request
handler.
Remove the code to get group membership and numeric UID information,
since neither should be necessary and don't appear to be used anywhere
else in the code base.
Add the additional Science Platform domains to the list of domains that
require authentication.
> [DM-28120] Support Gafaelfawr 2.0

- .gitignore
- docker-compose.yml
See https://github.com/Caltech-IPAC/firefly/pull/1167
> replace the old docker dev environment with something simple

- config/app.config
- docker-compose.yml
- settings.gradle
- src/suit/build.gradle
see https://github.com/Caltech-IPAC/firefly/pull/1192
> FIREFLY-932_upgrade_java_gradle

- src/suit/html/suit.html
Enable `useChartWorkArea` on `suit`(Rubin Science Platform Portal)
> FIREFLY-994_multi-table_chart_view

- config/app.config
> DM-35385: Update internal version to 2022.2.1

- compose.yml
- config/app.config
see https://github.com/Caltech-IPAC/firefly/pull/1307
> FIREFLY-1138: Make help base URL a runtime configuratable property

- config/app.config
- src/suit/html/suit-test.html
- src/suit/js/SUIT.js
- src/suit/js/actions.jsx
suit 2023.1
- update to config
- updates options
- update searchActionsCmdMask options
- build against firefly release-2023.1.0
> suit 2023.1

- src/suit/build.gradle
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1258
Please read.  Many details were added to the ticket.
> FIREFLY-1258: Use maven central where possible

- src/suit/js/RubinLanding.jsx
- src/suit/js/SUIT.js
See https://github.com/Caltech-IPAC/firefly/pull/1517
> FIREFLY-1427: Searches as menu items

- src/suit/jest.config.js
- src/suit/package.json
Fixes [FIREFLY-1522](https://jira.ipac.caltech.edu/browse/FIREFLY-1522)
See: https://github.com/Caltech-IPAC/firefly/pull/1598
> FIREFLY-1522: Extract jest config from firefly for reusing it in all apps

- src/suit/build.gradle
see https://github.com/IPAC-SW/irsa-ife/pull/358
> FIREFLY-1559: Upgrade Java from version 17 to 21

- src/suit/java/edu/caltech/ipac/lsst/security/LsstSsoAdapter.java
see https://github.com/Caltech-IPAC/firefly/pull/1760
> FIREFLY-1735:  Update LsstSSOAdapter to correctly extract a valid user ID from request headers

- config/app.config
- config/k8s/suit-int.yaml
- config/k8s/suit-stable.yaml
See [Firefly PR](https://github.com/Caltech-IPAC/firefly/pull/1737) for more details.
- adjust width
- fixed local docker build
> FIREFLY-1691: Job History

- src/suit/js/RubinLanding.jsx
See firefly PR: https://github.com/Caltech-IPAC/firefly/pull/1791
> FIREFLY-1754: Fix poor positioning of App Hints
